# emotion_questions.py

# A set of predefined questions to assess user emotions and generate reports based on their responses.

questions = [
    "How are you feeling today?",
    "What made you happy this week?",
    "Can you describe a moment when you felt really sad?",
    "What are you worried about right now?",
    "Have you felt anxious lately? If so, when?",
    "What is something you are grateful for today?",
    "How do you feel about your current situation?",
    "What is something that excites you?",
    "Can you recall a time when you felt proud of yourself?",
    "What do you do to cope with stress?",
    "How often do you feel overwhelmed?",
    "What is something that makes you feel loved?",
    "Can you share a recent experience that surprised you?",
    "How do you usually express your anger?",
    "What do you do when you feel lonely?",
    "How do you feel about your relationships with others?",
    "What is something that brings you peace?",
    "Can you describe a time when you felt hopeless?",
    "What are your thoughts on seeking help when you need it?",
    "How do you feel about your future?",
    "What is something you wish you could change about your life?",
    "How do you handle feelings of guilt or regret?",
    "What is your biggest fear?",
    "How do you feel when you achieve a goal?",
    "What do you do to lift your mood when you are down?",
    "How do you feel about taking risks?",
    "What is something that makes you feel anxious?",
    "How do you cope with feelings of sadness?",
    "What is your favorite way to relax?",
    "How do you feel about change?",
    "What is something that motivates you?",
    "How do you feel when you are surrounded by friends?",
    "What is your go-to activity when you need a break?",
    "What do you think about when you are alone?",
    "How do you feel about your work or studies?",
    "What is something that you are passionate about?",
    "How do you feel when you help others?",
    "What is your favorite memory?",
    "How do you feel about your body image?",
    "What is something that makes you feel anxious?",
    "How do you feel about your financial situation?",
    "What is your biggest regret?",
    "How do you feel about your family?",
    "What is something that you wish you could do?",
    "How do you feel when you receive compliments?",
    "What is your favorite way to express yourself?",
    "How do you feel about your friendships?",
    "What is something that you are looking forward to?",
    "How do you feel when you face challenges?",
    "What is your favorite way to spend a weekend?",
    "How do you feel about your daily routine?",
    "What is something that makes you feel fulfilled?",
    "How do you feel when you think about the future?",
    "What is your favorite way to celebrate achievements?",
    "How do you feel about your personal growth?",
    "What is something that you are proud of?",
    "How do you feel when you are in nature?",
    "What is your favorite way to connect with others?",
    "How do you feel about your hobbies?",
    "What is something that you find challenging?",
    "How do you feel when you are in a crowded place?",
    "What is your favorite way to unwind after a long day?",
    "How do you feel about your sleep habits?",
    "What is something that you wish you could learn?",
    "How do you feel when you think about your childhood?",
    "What is your favorite way to practice self-care?",
    "How do you feel about your community?",
    "What is something that you are curious about?",
    "How do you feel when you are in a new environment?",
    "What is your favorite way to express creativity?",
    "How do you feel about your achievements?",
    "What is something that you are grateful for in your life?",
    "How do you feel when you think about your relationships?",
    "What is your favorite way to spend time with family?",
    "How do you feel about your mental health?",
    "What is something that you find inspiring?",
    "How do you feel when you are under pressure?",
    "What is your favorite way to stay active?",
    "How do you feel about your personal values?",
    "What is something that you want to achieve in the next year?",
    "How do you feel when you think about your legacy?",
    "What is your favorite way to connect with your emotions?",
    "How do you feel about your life choices?",
    "What is something that you want to change in your life?",
    "How do you feel when you are in a quiet place?",
    "What is your favorite way to learn new things?",
    "How do you feel about your support system?",
    "What is something that you want to explore?",
    "How do you feel when you think about your goals?",
    "What is your favorite way to practice mindfulness?",
    "How do you feel about your self-esteem?",
    "What is something that you want to improve about yourself?",
    "How do you feel when you are with loved ones?",
    "What is your favorite way to express gratitude?",
    "How do you feel about your work-life balance?",
    "What is something that you want to accomplish this week?",
    "How do you feel when you think about your dreams?",
    "What is your favorite way to engage with your emotions?",
    "How do you feel about your decision-making skills?",
    "What is something that you want to prioritize in your life?",
    "How do you feel when you are in a leadership role?",
    "What is your favorite way to give back to the community?",
    "How do you feel about your time management skills?",
    "What is something that you want to achieve in your career?",
    "How do you feel when you think about your impact on others?",
    "What is your favorite way to celebrate small wins?",
    "How do you feel about your ability to adapt to change?",
    "What is something that you want to explore creatively?",
    "How do you feel when you are in a supportive environment?",
    "What is your favorite way to practice gratitude?",
    "How do you feel about your ability to handle criticism?",
    "What is something that you want to learn from others?",
    "How do you feel when you think about your personal goals?",
    "What is your favorite way to connect with your inner self?",
    "How do you feel about your ability to set boundaries?",
    "What is something that you want to achieve in your personal life?",
    "How do you feel when you are in a challenging situation?",
    "What is your favorite way to recharge?",
    "How do you feel about your ability to communicate effectively?",
    "What is something that you want to explore in your relationships?",
    "How do you feel when you think about your passions?",
    "What is your favorite way to engage with your community?",
    "How do you feel about your ability to express your needs?",
    "What is something that you want to achieve in your spiritual life?",
    "How do you feel when you are in a nurturing environment?",
    "What is your favorite way to practice self-reflection?",
    "How do you feel about your ability to forgive?",
    "What is something that you want to explore in your career?",
    "How do you feel when you think about your relationships with colleagues?",
    "What is your favorite way to practice empathy?",
    "How do you feel about your ability to manage stress?",
    "What is something that you want to achieve in your family life?",
    "How do you feel when you are in a collaborative environment?",
    "What is your favorite way to practice self-compassion?",
    "How do you feel about your ability to take risks?",
    "What is something that you want to explore in your personal development?",
    "How do you feel when you think about your friendships?",
    "What is your favorite way to practice resilience?",
    "How do you feel about your ability to learn from mistakes?",
    "What is something that you want to achieve in your health journey?",
    "How do you feel when you are in a positive environment?",
    "What is your favorite way to practice authenticity?",
    "How do you feel about your ability to inspire others?",
    "What is something that you want to explore in your creative expression?"
] 